export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_REQUESTING = 'AUTH_REQUESTING'
export const AUTH_FAIL = 'AUTH_FAIL'

export const CORDOVA_DEVICEREADY = 'CORDOVA_DEVICEREADY'
export const CORDOVA_ONLINE = 'CORDOVA_ONLINE'
export const CORDOVA_OFFLINE = 'CORDOVA_OFFLINE'
export const CORDOVA_SET_DEVICE = 'CORDOVA_SET_DEVICE'
export const CORDOVA_DEVICE_REGISTER = 'CORDOVA_DEVICE_REGISTER'

export const ACCOUNT_SUCCESS = 'ACCOUNT_SUCCESS'
export const ACCOUNT_REQUESTING = 'ACCOUNT_REQUESTING'
export const ACCOUNT_FAIL = 'ACCOUNT_FAIL'
